export const VARIABLES = [
    '--bs-blue',
    '--bs-indigo',
    '--bs-purple',
    '--bs-pink',
    '--bs-red',
    '--bs-orange',
    '--bs-yellow',
    '--bs-green',
    '--bs-teal',
    '--bs-cyan',
    '--bs-white',
    '--bs-gray',
    '--bs-gray-dark',
    '--bs-gray-100',
    '--bs-gray-200',
    '--bs-gray-300',
    '--bs-gray-400',
    '--bs-gray-500',
    '--bs-gray-600',
    '--bs-gray-700',
    '--bs-gray-800',
    '--bs-gray-900',
    '--bs-primary',
    '--bs-secondary',
    '--bs-success',
    '--bs-info',
    '--bs-warning',
    '--bs-danger',
    '--bs-light',
    '--bs-dark',
    '--bs-primary-rgb',
    '--bs-secondary-rgb',
    '--bs-success-rgb',
    '--bs-info-rgb',
    '--bs-warning-rgb',
    '--bs-danger-rgb',
    '--bs-light-rgb',
    '--bs-dark-rgb',
    '--bs-white-rgb',
    '--bs-black-rgb',
    '--bs-body-color-rgb',
    '--bs-body-bg-rgb',
    '--bs-font-sans-serif',
    '--bs-font-monospace',
    '--bs-gradient',
    '--bs-body-font-family',
    '--bs-body-font-size',
    '--bs-body-font-weight',
    '--bs-body-line-height',
    '--bs-body-color',
    '--bs-body-bg',
] as const;

export function getCssVariable( variable: typeof VARIABLES[number] ) {
    return getComputedStyle(document.body).getPropertyValue(variable);
}